"""RAMSES RF - Dataclass Payload Layer package.

This package provides the unified strongly-typed dataclass layer for RAMSES-II
packet payloads.
"""

from .adapters import payload_to_dict
from .base import PayloadBase
from .dhw import DhwConfigPayload, DhwModePayload, DhwParamsPayload, DhwStatePayload
from .heating import (
    BindingPayload,
    BoilerRelayDemandPayload,
    DhwTemperaturePayload,
    HeatDemandPayload,
    OutdoorTempPayload,
    ScheduleSwitchpointPayload,
    SetPointInfoPayload,
    SystemSyncPayload,
    TemperaturePayload,
    ZoneConfigPayload,
    ZoneSetpointPayload,
)
from .hvac import (
    AirQualityBasisPayload,
    Co2Payload,
    FanModePayload,
    HvacAirQualityPayload,
    HvacAutoRequestPayload,
    HvacBypassStatePayload,
    HvacCounterPayload,
    HvacDevicePairingPayload,
    HvacFanParamPayload,
    HvacFaultLogEntryPayload,
    HvacFaultStatusPayload,
    HvacFilterChangePayload,
    HvacProgrammeConfigPayload,
    HvacProgrammeEnabledPayload,
    HvacProgrammeSchemePayload,
    HvacVentilationStatusPayload,
    OutdoorHumidityPayload,
    RelativeHumidityPayload,
    SpiderThermostatPayload,
)
from .opentherm import (
    OpenthermBridgeStatusPayload,
    OpenthermCapacityPayload,
    OpenthermConfigPayload,
    OpenthermDiagnosticsPayload,
    OpenthermFrameExPayload,
    OpenthermModulationPayload,
    OpenThermMsgPayload,
    OpenthermParamsPayload,
    OpenthermSetpointPayload,
    OpenthermStatusPayload,
    OpenthermTemperaturePayload,
)
from .registry import (
    PAYLOAD_REGISTRY,
    PayloadRegistry,
    get_payload_class,
    register_payload,
)
from .system import (
    PuzzlePayload,
    SystemActuatorPayload,
    SystemChangeCounterPayload,
    SystemClockPayload,
    SystemConfigPayload,
    SystemDatePayload,
    SystemDeviceInfoPayload,
    SystemFaultLogPayload,
    SystemFaultPayload,
    SystemFlagPayload,
    SystemHeatCoolPayload,
    SystemLanguagePayload,
    SystemLogIndexPayload,
    SystemOpenthermBridgePayload,
    SystemOutdoorTempPayload,
    SystemParameterPayload,
    SystemRolePayload,
    SystemStatusPayload,
    SystemSyncHeartbeatPayload,
)

__all__ = [
    "PAYLOAD_REGISTRY",
    "AirQualityBasisPayload",
    "BindingPayload",
    "BoilerRelayDemandPayload",
    "Co2Payload",
    "DhwConfigPayload",
    "DhwModePayload",
    "DhwParamsPayload",
    "DhwStatePayload",
    "DhwTemperaturePayload",
    "FanModePayload",
    "HeatDemandPayload",
    "HvacAirQualityPayload",
    "HvacAutoRequestPayload",
    "HvacBypassStatePayload",
    "HvacCounterPayload",
    "HvacDevicePairingPayload",
    "HvacFanParamPayload",
    "HvacFaultLogEntryPayload",
    "HvacFaultStatusPayload",
    "HvacFilterChangePayload",
    "HvacProgrammeConfigPayload",
    "HvacProgrammeEnabledPayload",
    "HvacProgrammeSchemePayload",
    "HvacVentilationStatusPayload",
    "OpenThermMsgPayload",
    "OpenthermBridgeStatusPayload",
    "OpenthermCapacityPayload",
    "OpenthermConfigPayload",
    "OpenthermDiagnosticsPayload",
    "OpenthermFrameExPayload",
    "OpenthermModulationPayload",
    "OpenthermParamsPayload",
    "OpenthermSetpointPayload",
    "OpenthermStatusPayload",
    "OpenthermTemperaturePayload",
    "OutdoorHumidityPayload",
    "OutdoorTempPayload",
    "PayloadBase",
    "PayloadRegistry",
    "PuzzlePayload",
    "RelativeHumidityPayload",
    "ScheduleSwitchpointPayload",
    "SetPointInfoPayload",
    "SpiderThermostatPayload",
    "SystemActuatorPayload",
    "SystemChangeCounterPayload",
    "SystemClockPayload",
    "SystemConfigPayload",
    "SystemDatePayload",
    "SystemDeviceInfoPayload",
    "SystemFaultLogPayload",
    "SystemFaultPayload",
    "SystemFlagPayload",
    "SystemHeatCoolPayload",
    "SystemLanguagePayload",
    "SystemLogIndexPayload",
    "SystemOpenthermBridgePayload",
    "SystemOutdoorTempPayload",
    "SystemParameterPayload",
    "SystemRolePayload",
    "SystemStatusPayload",
    "SystemSyncHeartbeatPayload",
    "SystemSyncPayload",
    "TemperaturePayload",
    "ZoneConfigPayload",
    "ZoneSetpointPayload",
    "get_payload_class",
    "payload_to_dict",
    "register_payload",
]
