from __future__ import annotations

from typing import Any

from .serialutil import SerialException as SerialException

class Serial:
    """Minimal stub for pyserial's Serial class."""

    port: str | None
    @property
    def name(self) -> str: ...
    @property
    def portstr(self) -> str: ...
    @property
    def in_waiting(self) -> int: ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def close(self) -> None: ...
    def read(self, size: int = ...) -> bytes: ...
    def write(self, data: bytes | bytearray | memoryview) -> int: ...
    def set_low_latency_mode(self, latency_mode: bool = ...) -> None: ...

def serial_for_url(url: str, *args: Any, **kwargs: Any) -> Serial: ...
